[package]
name = "audio-kun"
version = "0.0.1"
edition = "2021"
description = "audio thing"
license = "MIT"
readme = "README.md"
repository = "https://github.com/NathanRoark/audio-kun"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
